excluded_measures:
- PWCCA
- GeometryScore
- IMDScore
threads: 1
cache_to_disk: true
cache_to_mem: false
only_extract_reps: true
rerun_nans: false
experiments:
- name: Vision Gauss R18 IN100 Experiments
  type: GroupSeparationExperiment
  representation_dataset: Gauss_Off_ImageNet100DataModule
  filter_key_vals:
    train_dataset:
    - Gauss_Max_ImageNet100DataModule
    - Gauss_L_ImageNet100DataModule
    - Gauss_M_ImageNet100DataModule
    - Gauss_S_ImageNet100DataModule
    - Gauss_Off_ImageNet100DataModule
    architecture:
    - ViT_L32
    - ViT_B32
    - ResNet18
    - ResNet34
    - ResNet101
    - VGG11
    - VGG19
    seed:
    - 0
    - 1
    - 2
    - 3
    - 4
    domain: VISION
  grouping_keys:
  - train_dataset
  separation_keys:
  - architecture
raw_results_filename: in100_augment.parquet
table_creation:
  save_full_df: true
  full_df_filename: in100_augment.csv
  save_aggregated_df: false
  row_index: similarity_measure
  columns:
  - identifier
  - representation_dataset
  - quality_measure
  - architecture
  value_key: value
  filename: in100_augment.xlsx
